#!/bin/bash

if [ $# -ne 1 ]
then
	echo "need one argument and one argument only"
	echo "enter a project name"
	exit -1
fi

eagledir="/c/Users/Freddy/Documents/eagle"

cp $eagledir/$1/eagle.epf $1/eagle_files/dev
cp $eagledir/$1/$1.sch $1/eagle_files/dev
cp $eagledir/$1/$1.brd $1/eagle_files/dev

cp $eagledir/$1/$1\.GBL $1/eagle_files/prod
cp $eagledir/$1/$1\.GBO $1/eagle_files/prod
cp $eagledir/$1/$1\.GBS $1/eagle_files/prod

cp $eagledir/$1/$1\.GTL $1/eagle_files/prod
cp $eagledir/$1/$1\.GTO $1/eagle_files/prod
cp $eagledir/$1/$1\.GTS $1/eagle_files/prod

cp $eagledir/$1/$1\.TXT $1/eagle_files/prod
